services:
  storage:
    image: redis

  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${DB_NAME:-todos_database}
    depends_on:
      - storage

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - mongodb

  counter:
    build: ./counter
    ports:
      - 81:3001
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    depends_on:
      - storage
      - mongodb

  library:
    build: ./library
    ports:
      - 80:3000
    environment:

      - PORT=3000
    depends_on:
      - mongodb
    env_file:
      - .env