services:
  storage:
    image: redis
  counter:
    build: ./counter
    ports:
      - 81:3001
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    depends_on:
      - storage
  library:
    build: ./library
    ports:
      - 80:3000
    environment:
      - PORT=3000
    depends_on:
      -  storage